version: '3.4'
services:
  api:
    build:
      dockerfile: ./docker/api.Dockerfile
      context: .
      target: development
    image: learn/nlw3-api
    container_name: nlw3-api
    ports:
      - "3333:3333"
    networks:
      - nlw3-network
    # depends_on:
    #   - db
    volumes:
      - "./api:/var/www"
      - "/var/www/node_modules"

  web:
    build:
      dockerfile: ./docker/web.Dockerfile
      context: .
      target: development
    image: learn/nlw3-web
    container_name: nlw3-web
    ports:
      - "3000:3000"
    networks:
      - nlw3-network
    depends_on:
      - api
    volumes:
      - "./web:/var/www"
      - "/var/www/node_modules"

  # mobile:
  #   build:
  #     dockerfile: ./docker/mobile.Dockerfile
  #     context: .
  #     target: development
  #   image: learn/nlw3-mobile
  #   container_name: nlw3-mobile
  #   ports:
  #     - "19000:19000"
  #   networks:
  #     - nlw3-network
  #   depends_on:
  #     - api
  #   volumes:
  #     - "./mobile:/var/www"
  #     - "/var/www/node_modules"

  # db:
  #   image:
  #   container_name: nlw3-db
  #   ports:
  #     - ""
  #   networks:
  #     - nlw3-network
  #   environment:
  #     PASS: ""
  #   volumes:
  #     - ""

networks:
  nlw3-network:
    driver: bridge
